### PR TITLE
feat: Adds a way to use generics with this library.

### PR DESCRIPTION
**Pull request by jfyne**
I am very open to changing this to another way, but I think this is pretty clean. Thanks for the library.

### CODE REVIEW

**Comment by jfyne** [comment]
This will also not break any existing code

**Comment by delijati** [comment]
@kofalt can this be merged!?

**Comment by natenho** [comment]
@kofalt , it would be great to include this generic feature as an evolution! 
The memoize.Call is also a better Go style name for the function, since the package name already has "memoize"

**Comment by kofalt** [comment]
Hi there @natenho, thanks for the ping. I will have a look at this tomorrow.

**Comment by kofalt** [comment]
Thanks for the PR @jfyne, I must not have had email notifications on when this was originally sent in.

I am merging with a second small change to bump the go version.

**Pull request merged**
